name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install poetry
        env:
          POETRY_VERSION: "1.1.13"
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry config virtualenvs.create false

      - name: cache poetry.lock dependencies
        id: cache-poetry-deps
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}-test-v1

      - name: install dependencies
        if: steps.cache-poetry-deps.outputs.cache-hit != 'true'
        run: poetry install

      - name: test and coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          SETLIST_FM_API_KEY: "DUMMY"
        run: |
          poetry run pytest --cov=. --cov-branch -v --durations=25
          poetry run coverage report -m
          poetry run codecov -F ${{ matrix.python-version }}
